// products file
const products = [
    {
        _id: '1',
        name: 'ABC',
        image: '/images/porschetaycan.jpg',
        description: 'Porsche has an electric vehicle now',
        brand: 'Porsche',
        category: 'Sports Car',
        price: 499.99,
        countInStock: 3,
        rating: 4.9,
        numReviews: 4,
    },
    {
        _id: '1',
        name: 'ABC',
        image: '/images/porschetaycan.jpg',
        description: 'Porsche has an electric vehicle now',
        brand: 'Porsche',
        category: 'Sports Car',
        price: 499.99,
        countInStock: 3,
        rating: 4.9,
        numReviews: 4,
    },
    {
        _id: '1',
        name: 'ABC',
        image: '/images/porschetaycan.jpg',
        description: 'Porsche has an electric vehicle now',
        brand: 'Porsche',
        category: 'Sports Car',
        price: 499.99,
        countInStock: 3,
        rating: 4.9,
        numReviews: 4,
    }
    ,
    {
        _id: '1',
        name: 'ABC',
        image: '/images/porschetaycan.jpg',
        description: 'Porsche has an electric vehicle now',
        brand: 'Porsche',
        category: 'Sports Car',
        price: 499.99,
        countInStock: 3,
        rating: 4.9,
        numReviews: 4,
    },
    {
        _id: '1',
        name: 'ABC',
        image: '/images/porschetaycan.jpg',
        description: 'Porsche has an electric vehicle now',
        brand: 'Porsche',
        category: 'Sports Car',
        price: 499.99,
        countInStock: 3,
        rating: 4.9,
        numReviews: 4,
    },
    {
        _id: '1',
        name: 'ABC',
        image: '/images/porschetaycan.jpg',
        description: 'Porsche has an electric vehicle now',
        brand: 'Porsche',
        category: 'Sports Car',
        price: 499.99,
        countInStock: 3,
        rating: 4.9,
        numReviews: 4,
    }
]

// export the products file
export default products;